routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('threads', 'ThreadController');
Route::resource('threads.replies', 'ReplyController');
Route::resource('replies.likes', 'ReplyLikeController');
Route::resource('categories', 'CategoryController');


Auth::routes();

Route::get('/', 'ThreadController@index');

app/Thread.php
<?php

namespace App;

use App\Traits\HasSlug;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Thread
 *
 * @package App
 */
class Thread extends Model
{
    use HasSlug;

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @var array
     */
    protected $with = [
        'user'
    ];

    /**
     * Boot
     */
    protected static function boot()
    {
        parent::boot();

        static::created(function ($thread) {
            $thread->update([
                'slug' => $thread->title
            ]);
        });
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    /**
     * @param int $limit
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function lastReply()
    {
        return $this->hasOne(Reply::class)
                ->latest();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return string
     */
    public function path()
    {
        return '/threads/' . $this->slug;
    }

    /**
     * @return mixed
     */
    public function author()
    {
        return $this->user->username;
    }

    /** @test
     * @param \App\Reply $reply
     *
     * @return mixed
     */
    public function addReply(Reply $reply)
    {
        return $this->replies()->save($reply);
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CreateThreadRequest;
use App\Reply;
use App\Thread;
use Illuminate\Http\Request;

class ThreadController extends Controller
{
    /**
     * ThreadController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->only('create', 'store', 'update', 'edit');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $threads = Thread::with('category', 'lastReply')
            ->withCount('replies')
            ->latest()
            ->paginate(10);

        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('threads.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CreateThreadRequest $request)
    {
        $thread = Thread::create([
            'user_id' => auth()->id(),
            'category_id' => $request->category_id,
            'title' => $request->title,
            'body' => $request->body
        ]);

        return redirect($thread->path());
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Thread $thread
     *
     * @return void
     */
    public function show(Thread $thread)
    {
        $thread->setRelation('replies', $thread->replies()->paginate(5));

        return view('threads.show', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/Thread.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Thread extends Component
{
    /**
     * @var \App\View\Components\Thread
     */
    public \App\Thread $thread;

    /**
     * Create a new component instance.
     *
     * @param \App\View\Components\Thread $thread
     */
    public function __construct(\App\Thread $thread)
    {
        $this->thread = $thread;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.thread');
    }
}

resources/views/threads/create.blade.php
<x-app>
    <div class="container mx-auto mt-10 px-2 md:px-0">
        <h1 class="text-2xl font-bold mb-5 px-2 md:px-0">Create Thread</h1>
        <div class="flex flex-wrap -mx-2">
            <aside class="w-full mb-5 md:w-1/4 px-2 md:order-2 md:mb-0">
                @include('threads.layouts.aside')
            </aside>
            <main class="w-full md:w-3/4 md:px-2">
                <div class="bg-white rounded p-5 mx-2 md:mx-0">

                    <form action="{{ route('threads.store') }}" method="post">
                        @csrf

                        <div class="md:flex md:items-center mb-6">
                            <div class="md:w-1/3">
                                <label for="email" class="block font-bold mb-1 md:mb-0 pr-4 text-gray-600 is-required">
                                    Title
                                </label>
                            </div>
                            <div class="md:w-2/3">
                                <input type="text" name="title" id="title"
                                       class="appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white"
                                       value="{{ old('title') }}"
                                >
                                @error('title')
                                <span class="text-sm text-red-500">{{ $errors->first('title') }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="md:flex md:items-center mb-6">
                            <div class="md:w-1/3">
                                <label for="category_id" class="block font-bold mb-1 md:mb-0 pr-4 text-gray-600 is-required">
                                    Category
                                </label>
                            </div>
                            <div class="md:w-2/3">
                                <select name="category_id" id="category_id"
                                        class="appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white"
                                >
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <span class="text-sm text-red-500">{{ $errors->first('category_id') }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="md:flex md:items-center mb-6">
                            <div class="md:w-1/3">
                                <label for="email" class="block font-bold mb-1 md:mb-0 pr-4 text-gray-600 is-required">
                                    Body
                                </label>
                            </div>
                            <div class="md:w-2/3">
                                <wysiwyg></wysiwyg>
                                @error('body')
                                <span class="text-sm text-red-500">{{ $errors->first('body') }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="md:flex md:items-center">
                            <div class="md:w-1/3"></div>
                            <div class="md:w-2/3">
                                <button class="button is-primary" type="submit">
                                    Create Thread
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </main>
        </div>
    </div>
</x-app>

resources/views/threads/index.blade.php
<x-app>
    <div class="container mx-auto mt-10 px-2 md:px-0">
        <h1 class="text-2xl font-bold mb-5 px-2 md:px-0">Threads</h1>
        <div class="flex flex-wrap -mx-2">
            <aside class="w-full mb-5 md:w-1/4 px-2 md:order-2 md:mb-0">
                <a href="{{ route('threads.create') }}" role="button" class="button is-primary mb-5">New Thread</a>

                @include('threads.layouts.aside')
            </aside>
            <main class="w-full md:w-3/4 md:px-2">
                <div class="bg-white rounded p-5 mx-2 md:mx-0">
                    @foreach ($threads as $thread)
                        <x-thread :thread="$thread"></x-thread>
                    @endforeach

                    <div class="px-3">
                        {{ $threads->links('pagination::tailwind') }}
                    </div>
                </div>
            </main>
        </div>
    </div>
</x-app>

resources/views/threads/show.blade.php
<x-app>
    <div class="container mx-auto mt-10 px-2 md:px-0">
        <h1 class="text-2xl font-bold mb-5 px-2 md:px-0">{{ $thread->title }}</h1>
        <div class="flex flex-wrap -mx-2">
            <aside class="w-full mb-5 md:w-1/4 px-2 md:order-2 md:mb-0">
                @include('threads.layouts.aside')
            </aside>
            <main class="w-full md:w-3/4 md:px-2">
                <div class="mb-5">
                    <div class="bg-green-300 rounded p-5 mx-2 md:mx-0">
                        <div class="flex justify-between mb-5">
                            <p class="font-bold text-sm text-green-100">{{ $thread->author() }}</p>
                            <p class="text-sm text-green-100">{{ $thread->created_at->diffForHumans() }}</p>
                        </div>

                        <div class="text-green-900">{!! $thread->body !!}</div>
                    </div>
                </div>

                {{--                Replies--}}
                <h2 class="text-2xl text-gray-600 font-bold mb-5 px-2 md:px-0">Comments</h2>

                @auth
                    <div class="bg-white p-5 mb-2">
                        <form method="post" action="{{ route('threads.replies.store', ['thread' => $thread->slug]) }}">
                            @csrf

                            <wysiwyg class="mb-2 trix"></wysiwyg>
                            @error('body')
                                <span class="text-sm text-red-500">{{ $errors->first('body') }}</span>
                            @enderror

                            <div class="flex justify-end">
                                <button type="submit" class="button is-primary">Reply</button>
                            </div>
                        </form>
                    </div>
                @endauth

                @foreach ($thread->replies as $reply)
                    <x-reply :reply="$reply" class="mb-2"></x-reply>
                @endforeach

                <div class="px-3">
                    {{ $thread->replies->links('pagination::tailwind') }}
                </div>
            </main>
        </div>
    </div>
</x-app>