routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('threads', 'ThreadController');
Route::resource('threads.replies', 'ReplyController');
Route::resource('replies.likes', 'ReplyLikeController');
Route::resource('categories', 'CategoryController');


Auth::routes();

Route::get('/', 'ThreadController@index');

app/Category.php
<?php

namespace App;

use App\Traits\HasSlug;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * Class Category
 *
 * @package App
 */
class Category extends Model
{
    use HasSlug;

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * Boot
     */
    protected static function boot()
    {
        parent::boot();

        static::created(function ($category) {
            $category->update([
                'slug' => $category->name
            ]);
        });
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function threads()
    {
        return $this->hasMany(Thread::class);
    }

    /**
     * @return string
     */
    public function path()
    {
        return '/categories/' . $this->slug;
    }

    /**
     * @return string
     */
    public function hex()
    {
        return $this->hex ? '#' . $this->hex : '#000';
    }

    /**
     * @param $value
     *
     * @return string
     */
    public function getDescriptionAttribute($value)
    {
        return Str::limit($value, 200);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Reply;
use App\Thread;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('name')->paginate(10);

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $threads = $category->threads()->orderBy('created_at')
            ->paginate();

        return view('categories.show', compact('category', 'threads'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/categories/index.blade.php
<x-app>
    <div class="container mx-auto mt-10 px-2 md:px-0">
        <h1 class="text-2xl font-bold mb-5 px-2 md:px-0">Categories</h1>
        <div class="flex flex-wrap -mx-2">
            <aside class="w-full mb-5 md:w-1/4 px-2 md:order-2 md:mb-0">
                @include('threads.layouts.aside')
            </aside>
            <main class="w-full md:w-3/4 md:px-2">
                <div class="bg-white rounded p-5 mx-2 md:mx-0">
                    @foreach ($categories as $category)
                        <div class="flex flex-col mb-5 p-3 border-b justify-between rounded hover:bg-gray-100 md:flex-row">
                            <div class="flex flex-col mb-4 md:mb-5">
                                <h4 class="text-lg">
                                    <a href="{{ $category->path() }}">{{ $category->name }}</a>
                                </h4>
                                <p class="text-sm text-gray-600">{{ $category->description }}</p>
                            </div>
                        </div>
                    @endforeach

                    <div class="px-3">
                        {{ $categories->links('pagination::tailwind') }}
                    </div>
                </div>
            </main>
        </div>
    </div>
</x-app>

resources/views/categories/show.blade.php
<x-app>
    <div class="container mx-auto mt-10">
        <h1 class="text-2xl font-bold mb-5 px-2 md:px-0">{{ $category->name }}</h1>
        <div class="flex flex-wrap -mx-2">
            <aside class="w-full mb-5 md:w-1/4 px-2 md:order-2 md:mb-0">
                @include('threads.layouts.aside')
            </aside>
            <main class="w-full md:w-3/4 md:px-2">
                <div class="bg-white rounded p-5 mx-2 md:mx-0">
                    @foreach ($threads as $thread)
                        <x-thread :thread="$thread"></x-thread>
                    @endforeach

                    <div>
                        {{ $threads->links('pagination::tailwind') }}
                    </div>
                </div>
            </main>
        </div>
    </div>
</x-app>